//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dostavka.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Analytics
    {
        public int ID_analytic { get; set; }
        public string Metric_type { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
