//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dostavka.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DostavkaEntities : DbContext
    {
        public DostavkaEntities()
            : base("name=DostavkaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Analytics> Analytics { get; set; }
        public virtual DbSet<Delivery_Routes> Delivery_Routes { get; set; }
        public virtual DbSet<Driver_Status> Driver_Status { get; set; }
        public virtual DbSet<Notifications> Notifications { get; set; }
        public virtual DbSet<Order_Items> Order_Items { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Payment_Transactions> Payment_Transactions { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Reviews> Reviews { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User_Preferences> User_Preferences { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
