//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dostavka.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notifications
    {
        public int ID_Notification { get; set; }
        public Nullable<int> ID_User { get; set; }
        public Nullable<int> ID_Order { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> Time_of_sending { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Users Users { get; set; }
    }
}
