//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dostavka.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment_Transactions
    {
        public int ID_Transaction { get; set; }
        public Nullable<int> ID_Order { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Payment_method { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
