//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dostavka.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Preferences
    {
        public int ID_Preference { get; set; }
        public Nullable<int> ID_Customer { get; set; }
        public Nullable<int> ID_preference_Product { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Users Users { get; set; }
    }
}
