//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int feedback_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> driver_id { get; set; }
        public Nullable<int> rating { get; set; }
        public Nullable<int> punctuality_rating { get; set; }
        public Nullable<int> politeness_rating { get; set; }
        public Nullable<int> cleanliness_rating { get; set; }
        public string comment { get; set; }
    
        public virtual Drivers Drivers { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
