//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTracking
    {
        public int tracking_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public string location { get; set; }
        public string status { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
