//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleAssignments
    {
        public int assignment_id { get; set; }
        public Nullable<int> vehicle_id { get; set; }
        public Nullable<int> driver_id { get; set; }
        public Nullable<System.DateTime> assigned_date { get; set; }
        public Nullable<System.DateTime> returned_date { get; set; }
    
        public virtual Drivers Drivers { get; set; }
        public virtual Vehicles Vehicles { get; set; }
    }
}
